### ISSUE TITLE
`datasource_id` returned by `querying.get_workbook_connections_dataframe` function does not match with actual datasource id

### ISSUE THREAD

**Issue by zhaisw** [divinorum-webb/tableau-api-lib#100]
When using function `querying.get_workbook_connections_dataframe` to query workbook connections, the `datasource_id` column in the returned dataframe does not match `datasource id` got from `querying.get_datasources_dataframe`.

Can you please check whether this issue exists? Thanks.

**Comment by divinorum-webb** [comment]
Hey @zhaisw, `tableau-api-lib` is a library which makes it possible to query Tableau's endpoints but it does not have control over how Tableau defines the responses returned by any given endpoint they have developed.

From playing with the Metadata API a bit and exploring the properties of the workbook, its connection, and the related datasource, my suspicion is that Tableau is providing the `id` for the datasource, which is not the same as the `luid` (local unique identifier) which is typically aliases as `id` in the REST API.

As far as this library goes, the payload received from Tableau Server is accurately being converted into a DataFrame and the `id` field they return for the named `datasource` is being populated into `datasource_id` in the resulting DataFrame.

The sample payload below is what comes from the raw endpoint for `Query Workbook Connections`:
```
{'connections': {'connection': [{'datasource': {'id': '07646e0f-3adf-4010-ab0e-abe15b0ae184',
     'name': 'crypto_prices Extract'},
    'id': 'd4db3e27-3c2a-4205-ace0-42f0f2cddc4d',
    'type': 'hyper',
    'embedPassword': False,
    'serverAddress': '',
    'serverPort': '0',
    'userName': 'tableau_internal_user',
    'queryTaggingEnabled': False}]}}
```

This library flattens that JSON response and loads it into a Pandas DataFrame, but the fact that Tableau is not returning the luid (local unique identifier) as the `id` field for the datasource is out of this library's control.

I'll drop a message to Tableau in their community channels, and I recommend you do the same!

**Comment by zhaisw** [comment]
Thank you so much for your explanation and detailed information. I will raise the issue to Tableau community as well.
The library helps a lot, thank you! Cheers!

**Comment by divinorum-webb** [comment]
@zhaisw check out the community slack channel for the DataDev community. It's a Tableau development community, focused on tools like the REST API and Metdata API rather than the analytics/data visualization side of things.
https://community.tableau.com/s/question/0D54T00000C5OqVSAV/join-the-datadev-slack

I posted a question about this topic in their slack channel `help-rest-api`.
