### ISSUE TITLE
conn.Publish_workbook - Permission Denied

### ISSUE THREAD

**Issue by Delboy007** [divinorum-webb/tableau-api-lib#118]
Similar to issue 6 (https://github.com/divinorum-webb/tableau-api-lib/issues/6), I'm getting a permission denied Error when trying to publish a workbook using my local file path,

response = conn.publish_workbook(workbook_file_path=YOUR_WORKBOOK_FILE_PATH,
workbook_name=YOUR_WORKBOOK_NAME,
project_id=YOUR_PROJECT_ID,
server_address=YOUR_DB_SERVER_ADDRESS,
port_number=YOUR_DB_PORT_NUMBER,
connection_username=YOUR_DB_USERNAME,
connection_password=YOUR_DB_PASSWORD,
embed_credentials_flag=YOUR_EMBED_FLAG)

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Documents\\Tableau'

What could the issue be as I do have access to the folder

**Comment by Delboy007** [comment]
I found the issue. The workbook_file_path needs to have the Tableau file name included in the path too.

**Comment by divinorum-webb** [comment]
Nice work debugging it yourself!
