### ISSUE TITLE
Response result encoding error

### ISSUE THREAD

**Issue by CG0047** [divinorum-webb/tableau-api-lib#12]
Hello，my use get_view_data_dataframe func find tableau view data，return DataFrame data exists Chinese coding error。

for solve this problem，I'm here src/tableau_api_lib/tableau_server_connection.query_view_data()，in return response Previous line add response.encoding = response.apparent_encoding，Got a short fix。

coding Examples：

@verify_api_method_exists('2.8')
def query_view_data(self,
                    view_id,
                    parameter_dict=None):
    """
    Queries the underlying data within the specified view.
    Note that the CSV content is accessible via the 'content' attribute, for example response.content
    :param string view_id: the view ID
    :param dict parameter_dict: dict defining url parameters for API endpoint
    :return: HTTP response
    """
    self.active_endpoint = ViewEndpoint(ts_connection=self,
                                        view_id=view_id,
                                        query_view_data=True,
                                        parameter_dict=parameter_dict).get_endpoint()
    self.active_headers = self.default_headers
    response = requests.get(url=self.active_endpoint, headers=self.active_headers, verify=self.ssl_verify)
    response.encoding = response.apparent_encoding
    return response

Thank you for reading~~

**Comment by divinorum-webb** [comment]
Hi, would this be impacting all endpoints or is this specific to querying view data? I'll take a look at adding the `apparent_encoding`.

**Comment by CG0047** [comment]
yes, impacting all endpoints, Thank you~

**Comment by divinorum-webb** [comment]
Hi @CG0047 a parameter has been added to `TableauServerConnection` that supports using apparent encoding.

You can enable apparent encoding by setting the parameter `use_apparent_encoding` to `True` when initializing an instance of Tableau Server Connection:

`conn = TableauServerConnection(config, env='my_env', use_apparent_encoding=True)`
