### ISSUE TITLE
Images are missing in published Dashboards

### ISSUE THREAD

**Issue by BernardoGui** [divinorum-webb/tableau-api-lib#16]
When publishing it seems that  'External Files' are not included. Did not see a flag to change that.

**Comment by divinorum-webb** [comment]
Hi Bernardo, I'm not seeing such a flag in the REST API reference:
https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm#publish_workbook
https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm#publish_data_source

If Tableau makes this option available to the publishing endpoints of the REST API reference, then we'll add it in.
