### ISSUE TITLE
Problems after publishing workbook

### ISSUE THREAD

**Issue by dreamca4er** [divinorum-webb/tableau-api-lib#24]
**Prerequisites**:

- python3.7
- tableau-api-lib==0.1.1
- Tableau 2021.1.0 (20211.21.0409.0059)
- Workbook with one embedded BigQuery datasource

**My actions:**

1. Acquire conn (TableauServerConnection object)
2. Publish twbx workbook using conn.publish_workbook.
```
response = conn.publish_workbook(workbook_file_path=twbx_file_location, workbook_name=resource_name, project_id=project_id).json()
```
3. Embed BigQuery credentials into workbook's datasource using Tableau web UI (these credentials are 100% valid as I use them in >200 datasources and workbooks).
4. Try to refresh extracts or change connection type to Live.

**What do i get:**
Red popup from Tableau
```
Error:
Error:Missing or incorrect embedded credentials. Use 'Edit Connection' to fix embedded credentials.
```
But after publishing the same workbook using Tableau Desktop everything seems to be fine, no errors changing connection type or refreshing extracts.
P.S.
Publishing datasources using lib works just fine.

**Comment by divinorum-webb** [comment]
Hi, thanks for reporting the issue! Looking into reproducing it locally and then I'll follow up with you here.

**Comment by divinorum-webb** [comment]
Hey @dreamca4er, in my testing I encountered the exact same issue and it was resolved by passing a port number when publishing the workbook.

The port number must be passed as a string, and for me passing "0" worked for a BigQuery table extract.
Here are my connection details as a reference:

```
response = conn.publish_workbook(
    workbook_file_path="BigQuery Extract Workbook1.twbx",
    workbook_name="twbx_bigquery_extract_api1",
    project_id=<my_project_id>,
    server_address="https://content-autofill.googleapis.com/",
    connection_username=<my_username>,
    connection_password=<my_password>,
    port_number="0",
    embed_credentials_flag=True,
)
```

Until I work in a permanent fix, this should do the trick for you. I'll see if there is a viable way to assume port number values when none is passed, and if there is a good way to do this I will add it to the library.

Hope that helps!

**Comment by dreamca4er** [comment]
I used your connection parameters, but the same error occurred, adding or removing `port_number` parameter did nothing. But when I added `oauth_flag=True`, everything seemed to work:) So, I guess my problem is solved, thanks a lot!
