### ISSUE TITLE
Wrong version control.

### ISSUE THREAD

**Issue by mekvd** [divinorum-webb/tableau-api-lib#27]
For get workbook pdf method there are minimum version 3.8, but when i use my version 3.10, which is greater it breaks down.
These happens because of wrong numeration by Tableau. In there mind 3.1,3.2 and then 3.10, but for python comparison for float type it is wrong.

**Comment by divinorum-webb** [comment]
@mekvd what version of the library are you running? We saw a similar issue months ago but patched it and when testing just now, using the `download_workbook_pdf` method works as expected.
Please run `pip install -U tableau-api-lib` and verify if you still have the issue after upgrading the library.

**Comment by divinorum-webb** [comment]
Hi @mekvd, can you please confirm if upgrading the library resolves this issue?
In local tests, using API versions of `3.10` or `3.11` are working as intended.

Thank you for raising the issue! It's people like you that help make the library better.
