### ISSUE TITLE
typeguard preventing use of module

### ISSUE THREAD

**Issue by lerenah** [divinorum-webb/tableau-api-lib#28]
Currently on version 0.1.1, if you try to import tableau_api_lib, it will break because of a sudden dependency on typeguard:

"/opt/anaconda/lib/python3.6/site-packages/tableau_api_lib/utils/pagination
.py", line 4, in <module>
    from typeguard import typechecked
ModuleNotFoundError: No module named 'typeguard'

**Comment by divinorum-webb** [comment]
Hi @lerenah thank you for calling attention to this and sorry for the inconvenience. This was my fault in not adding `typeguard` to the `setup.py` requirements, which has now been updated.

Please run `pip install -U tableau-api-lib` and reply here if this resolves your issue.

**Comment by lerenah** [comment]
Ok thanks for confirming!  We're good to go now. Cheers!
