### ISSUE TITLE
How does Run Extract Refresh Task maps to tableau-api-lib?

### ISSUE THREAD

**Issue by lukezamboni** [divinorum-webb/tableau-api-lib#33]
https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_jobs_tasks_and_schedules.htm#run_extract_refresh_task

Couldn't figure this one out as it seems to behave differently from most other methods.

**Comment by divinorum-webb** [comment]
Hey @lukezamboni did you end up finding the answer? Let me know if you have any follow-up questions!

**Comment by lukezamboni** [comment]
Yes! I found your very useful tutorial on Medium :)

Thank you.
