### ISSUE TITLE
Problems with get_workbooks_dataframe @ Tableau API 3.12

### ISSUE THREAD

**Issue by dreamca4er** [divinorum-webb/tableau-api-lib#38]
**Python version:** 3.7.9
**tableau-api-lib version:** 0.1.14
**Tableau API version:** 3.12

**Problem:**
While using **tableau_api_lib.utils.querying. get_workbooks_dataframe** function with these specs an error occurs

```
tableau_api_lib.exceptions.tableau_server_exceptions.PaginationError: 
        The Tableau Server REST API method query_workbooks_for_site did not return paginated results. 
        Please verify that your connection is logged in and has a valid auth token.
        If using personal access tokens, note that only one session can be active at a time using a single token.
        Also note that the extract_pages() method wrapping this call is intended for paginated results only.
        Not all Tableau Server REST API methods support pagination. 
```

After a little debugging we can find out that **query_workbooks_for_site** method executes bad request, with this response:
```
{'error': {'summary': 'Bad Request', 'detail': "There was a problem querying the workbooks of user '<MY_USER_ID>'.", 'code': '400023'}}
```

The reason of this is that **get_workbooks_dataframe** function is requesting workbooks for site with following URL:

```https://<MY_URL>/api/3.12/sites/<MY_SITE_ID>/workbooks?fields=_all_&pageNumber=1&pageSize=100```

It seems that the problem is with **fields** parameter, without it everything seems to work fine.

**Comment by divinorum-webb** [comment]
@dreamca4er thanks for diving down that rabbit hole and figuring this out. This indeed seems to be a new issue for 3.12. I have asked Tableau about if this is intended or not, as it appears only Tableau Online is impacted right now. That is, I do not see any documentation for the Tableau REST API for 3.12 yet on the API reference.

If this is an intended change then I will modify the `tableau-api-lib` library to dynamically determine that url parameter name based on the API version defined.

I'll follow up once I hear back from Tableau. I've also kicked off a thread in their DataDev slack channel, specifically in the channel `help-rest-api`.

**Comment by dreamca4er** [comment]
To be even more precise, **_default_** fields value still works, as well as custom values like owner or project. Looks like only *_all_* predefined expression is affected.

**Comment by divinorum-webb** [comment]
Following up here, Tableau has filed an internal ticket to investigate the issue with the `_all_` fields parameter. In my own testing, this `_all_` fields parameter still works correctly for all endpoints except for the `Query Workbooks for Site` endpoint.

Until Tableau patches the issue, interacting with Tableau Online or Tableau Server environments running API version 3.12 will error out when using the `_all_` endpoint when querying workbooks.

The main thing impacted for the `tableau-api-lib` library is the `querying.get_workbooks_dataframe` function, which relies on the `_all_` fields parameter. To work around this, you can use the library's `query_workbooks_on_site` method and implement pagination manually with the `utils.pagination.extract_pages` function.

**Comment by divinorum-webb** [comment]
@dreamca4er given how long the underlying endpoint has been impacted, I made the decision to not use `_all_` fields by default. The `querying.get_workbooks_dataframe` function has recently been changed to:

```
def get_workbooks_dataframe(conn: TableauServerConnection, all_fields: bool = False) -> pd.DataFrame:
    """Returns a DataFrame describing all available workbooks. If none are available, an empty DataFrame is returned."""
    try:
        workbooks_df = pd.DataFrame(get_all_workbook_fields(conn=conn, all_fields=all_fields))
    except ContentNotFound:
        workbooks_df = pd.DataFrame()
    return workbooks_df
```

So you can now use the function without error, but it does not fetch some of the available fields that are documented in the REST API reference when using the `_all_` parameter. At any point you can try calling on that function with the `all_fields` param as `True` and if that fails, that means the issue continues.
