### ISSUE TITLE
Cannot read foreign language

### ISSUE THREAD

**Issue by ericmli419** [divinorum-webb/tableau-api-lib#39]
I am querying data from a workbook that contains foreign language (mostly chinese) but it is not reading properly. For example, this is showing up "é»å±±å±åå½" as country when it should be "黑山共和国".

**Comment by suzuke** [comment]
set use_apparent_encoding=True in TableauServerConnection may help.

**Comment by divinorum-webb** [comment]
@ericmli419 Can you please try setting the `use_apparent_encoding` flag to True when initializing your TableauServerConnection instance as @suzuke said and then follow up on this thread if that resolves the issue for you?

Thanks @suzuke !

**Comment by ericmli419** [comment]
That works! Thanks so much!
