### ISSUE TITLE
clone_schedules fails multiple calls

### ISSUE THREAD

**Issue by joetristano** [divinorum-webb/tableau-api-lib#4]
Hi,
We are trying to use the clone schedule functionality from 2019.4.1 to 2020.2
We want to migrate all schedules in bulk before we migrate content.
Line 20 of schedule.py fails with an exception on the any(schedule_names) call since the default is none and any fails with a non iterable.   Even if we pass schedules in ,  the code throws an exception with a key error on line 23.

This functionality would help us tremendously so I'm hoping we can use it.   We are basically just setting up 2 connections and calling clone_schedules.  

Thoughts?

Thanks
Joe

**Comment by divinorum-webb** [comment]
_Hey Joe, where you goin' with that gun in your hand?_ 

Had to get that Hendrix reference out of my system.

The issue should be resolved, go ahead and upgrade the library in your local environment (pip install --upgrade tableau-api-lib) and try running your program.

Let me know how if you have any trouble with it.

**Comment by joetristano** [comment]
Thank you Elliot!  You'll need to update your example to use a list
#estam_schedules_df = schedules_df.loc[schedules_df['name'].str.contains('estam')]['name'].tolist()
