### ISSUE TITLE
Get flow run method is not supported

### ISSUE THREAD

**Issue by Deepika1495** [divinorum-webb/tableau-api-lib#58]
I want to check the status of a flow I just triggered using `run_flow_now()` method. 
There seems to be no support for get_flow_run Tableau API in tableau-api-lib.- https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_flow.htm#get_flow_run .

**Comment by divinorum-webb** [comment]
@Deepika1495 can you try installing the latest version with `pip install -U tableau-api-lib` and follow up if the issue is resolved for you?

**Comment by divinorum-webb** [comment]
Checking in if the latest version of the library has this issue fixed for you?
