### ISSUE TITLE
Permission Denied 

### ISSUE THREAD

**Issue by mdabrar4devops** [divinorum-webb/tableau-api-lib#6]
response = conn.publish_workbook(workbook_file_path=YOUR_WORKBOOK_FILE_PATH, 
                                 workbook_name=YOUR_WORKBOOK_NAME, 
                                 project_id=YOUR_PROJECT_ID, 
                                 server_address=YOUR_DB_SERVER_ADDRESS,
                                 port_number=YOUR_DB_PORT_NUMBER,
                                 connection_username=YOUR_DB_USERNAME,
                                 connection_password=YOUR_DB_PASSWORD, 
                                 embed_credentials_flag=YOUR_EMBED_FLAG)
I have set all these parameters correct and workbook name is Test.twb and path is C:/Users/MyUser/Documents but it says permission denied

**Comment by divinorum-webb** [comment]
Can you post the full error? It isn't clear to me whether you are getting a permission error from Tableau Server or if it's a permission error from your file system. If it's from Tableau Server, you might want to check that you have permissions to publish. If it's a file system issue, that's an entirely different issue outside the scope of this library.
