### ISSUE TITLE
Need to add new permission object

### ISSUE THREAD

**Issue by rahulhacker** [divinorum-webb/tableau-api-lib#63]
https://github.com/divinorum-webb/tableau-api-lib/blob/2b6a8eaadda51c8e1be2bc2116ebc5d2352a3aee/src/tableau_api_lib/api_endpoints/permissions_endpoint.py#L84

For querying default permission for project, workbook, datasources is working as expected but the below line items are not working. As we saw that these are not added in the valid_project_permissions_object method.  For working it, made changes in my library locally.

1)DataRoles
2)Metrics
3)Lenses

**Comment by divinorum-webb** [comment]
Hey @rahulhacker thanks for raising this point. I will take a closer look and integrate any resulting improvements in an upcoming patch. Appreciate the feedback! This opened issue will remain open until the changes are in the library.

**Comment by divinorum-webb** [comment]
@rahulhacker if you `pip install -U tableau-api-lib`, the latest version adds support for the three items: dataroles, metrics, and lenses. Please confirm if the updates have resolved your issue.

**Comment by rahulhacker** [comment]
Yes, the issue has been resolved.
