### ISSUE TITLE
create_group might create the wrong field in request

### ISSUE THREAD

**Issue by harrismcgehee** [divinorum-webb/tableau-api-lib#69]
`conn.create_group(group_name = "test", minimum_site_role = "Explorer")`

yields

Deserialization problem: Unrecognized field \"**siteRole**\" (class com.tableausoftware.api.rest.viewmodels.GroupType), not marked as ignorable (6 known properties: \"domain\", \"import\", \"id\", \"userCount\", \"name\", \"**minimumSiteRole**\"])\n at [Source: (StringReader); line: 1, column: 72] (through reference chain: com.tableausoftware.api.rest.viewmodels.TsRequest[\"group\"]->com.tableausoftware.api.rest.viewmodels.GroupType[\"siteRole\"]);

**Comment by divinorum-webb** [comment]
I'll take a look, can you also share which tableau server version you are on?
