### ISSUE TITLE
Zero usage statistics in get_views_dataframe @ Tableau API 3.15

### ISSUE THREAD

**Issue by dreamca4er** [divinorum-webb/tableau-api-lib#72]
**Python version**: 3.7.13
**tableau-api-lib version**: 0.1.31
**Tableau API version**: 3.15

**get_views_dataframe** returns all zeros in usage_totalViewCount column. Digging deeper we can find that get_views_dataframe calls **get_all_view_fields** function and that function gets views via calling extract_pages on TableauServerConnection method **query_views_for_site**. query_views_for_site doesnt return usage statistics without parameter **includeUsageStatistics** set to true.

**Comment by divinorum-webb** [comment]
Thanks for the feedback, I have added the `querying.get_all_view_fields` querying utils function.
Run `pip install -U tableau-api-lib` and you'll have that update!

If you want the most accurate picture of your view/dashboard usage, I recommend tapping into the Tableau Server Repository (assuming you are on Tableau Server), where you have access to a wealth of data points on view counts. In the log files for the server, you'll find even more information that can be parsed including load times, who viewed what, etc.
