### ISSUE TITLE
Sign in with SSL

### ISSUE THREAD

**Issue by borissl-tr** [divinorum-webb/tableau-api-lib#79]
Hi, can you help me to define a connection to this library by SSL?

I have an error:
requests.exceptions.SSLError: HTTPSConnectionPool(host='reports.etorocorp.com', port=443): Max retries exceeded with url: //api/3.14/serverinfo (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

Defenition of code:
conn = TableauServerConnection(config_json=tableau_server_config, env='tableau_prod', ssl_verify=True)
conn.sign_in()
from tableau_api_l

**Comment by divinorum-webb** [comment]
Hi @borissl-tr, SSL certificate issues are not something the library has power over. However, if your server does not have SSL or if you do not want to verify SSL you can set the `ssl_verify` flag to `False`.

If your server does use SSL and you are having trouble with it, then I recommend speaking with your infrastructure or IT experts who may be able to provide details about why your attempts to reach the server via REST API are failing and how to solve the issue.

Some key words to help drive that conversation could be asking about the implications of an air-gapped server, having a load balancer, using a proxy server, etc. You could start by explaining that you are trying to make API calls to the Tableau Server and are not able to verify the local issuer certificate (share the error you shared here).

Hope that helps!
