### ISSUE TITLE
Revision history migration

### ISSUE THREAD

**Issue by vegi1979** [divinorum-webb/tableau-api-lib#8]
Hi Devyx  Thank you for the code it really helped.Have a question can we copy Revision history from Source Workbook to destination work book .. I have seen Clone_Projects,Clone_sites ,clone_schedules and Clone_workbooks but cant find any section to move version history ... Can you please let me know if we have any option to move or clone revision history...
Thank You

**Comment by divinorum-webb** [comment]
I don't think there is an elegant solution existing to migrating version history via REST API. To copy the entire workbook revision history, I can think of three potential methods:

1) Use the API call that downloads a [specific workbook revision](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm#download_workbook_revision). You would probably need to query the workbooks first to identify how many revisions exist, and then iterate X number of times to download each revision and publish each to your destination.
2) Generate a .tsbak backup file for your server, and restore this backup to the new server.
3) Use the Tableau Migration Tool
