### ISSUE TITLE
Issue with concat in flatten_dict_list_column

### ISSUE THREAD

**Issue by Ventrilok** [divinorum-webb/tableau-api-lib#81]
Hello Elliott,

I'm reaching at you to raise an issue with the contact function in flatten_dict_list_column (utils/common.py). I'm using (v0.1.36) and I get an error when using the flatten_dict_list_column after a quick investigation, I believe the line 44
`flattened_col_df = flattened_col_df.concat(temp_df) `
need to be replace by  
`flattened_col_df =  pd.concat([flattened_col_df, temp_df])`

Thank a lot in advance and also for this lib

Best regards

Pierre-Benoît

**Comment by divinorum-webb** [comment]
@Ventrilok thanks for raising the issue! Running `pip install -U tableau-api-lib` will pull in the latest changes which correct the issue.
