### ISSUE TITLE
KeyError: 'content' with subscriptions dataframe

### ISSUE THREAD

**Issue by mlaflash** [divinorum-webb/tableau-api-lib#83]
I am able to connect to Tableau server just fine and I have confirmed that I am using the most recent version, but when I run get_subscriptions_dataframe(conn) I get the following KeyError:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2645             try:
-> 2646                 return self._engine.get_loc(key)
   2647             except KeyError:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'content'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~\Anaconda3\lib\site-packages\tableau_api_lib\utils\common.py in flatten_dict_column(df, keys, col_name, add_col_prefix)
     20             if add_col_prefix is True:
---> 21                 df[col_name + "_" + key] = df[col_name].apply(lambda col: col[key])
     22             elif add_col_prefix is False:

~\Anaconda3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2799                 return self._getitem_multilevel(key)
-> 2800             indexer = self.columns.get_loc(key)
   2801             if is_integer(indexer):

~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2647             except KeyError:
-> 2648                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2649         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'content'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-51-91cf94121bd8> in <module>
----> 1 subscriptions_df = get_subscriptions_dataframe(conn)
      2 
      3 print (subscriptions_df)

~\Anaconda3\lib\site-packages\tableau_api_lib\utils\querying\subscriptions.py in get_subscriptions_dataframe(conn)
     17 def get_subscriptions_dataframe(conn):
     18     subscriptions_df = pd.DataFrame(get_all_subscription_fields(conn))
---> 19     subscriptions_df = flatten_dict_column(subscriptions_df, keys=['id', 'type'], col_name='content')
     20     subscriptions_df = flatten_dict_column(subscriptions_df, keys=['id', 'name'], col_name='schedule')
     21     subscriptions_df = flatten_dict_column(subscriptions_df, keys=['id', 'name'], col_name='user')

~\Anaconda3\lib\site-packages\tableau_api_lib\utils\common.py in flatten_dict_column(df, keys, col_name, add_col_prefix)
     28     except KeyError:
     29         # TODO(elliott): change the `col_name` reference below be the key name when the key is what's missing
---> 30         raise KeyError(f"No column named '{col_name}' was found in the DataFrame provided.")
     31 
     32 

KeyError: "No column named 'content' was found in the DataFrame provided."

**Comment by divinorum-webb** [comment]
Hey @mlaflash I just reproduced this error by deleting all my subscriptions in a sandbox server and using the `get_subscriptions_dataframe` function when no subscriptons were available.

It's a nasty looking error that happens when zero subscriptions exist in the DataFrame. I'll add an update that gives a more user-friendly error indicating no subscriptions were found.

**Comment by divinorum-webb** [comment]
If you update the library with `pip install -U tableau-api-lib`, you should no longer get this error when no subscriptions are returned from the underlying API request. You will now have an empty Pandas DataFrame.
