### ISSUE TITLE
Tableau Cloud/Online ?

### ISSUE THREAD

**Issue by ascendmgt** [divinorum-webb/tableau-api-lib#90]
Hi,
Can you let me know the required settings to make this work with Tableau Online/Cloud rather than Server?

**Comment by divinorum-webb** [comment]
@ascendmgt the REST API works in the same way on Tableau Server as Tableau Online. 

You can think of Tableau Online as a big Tableau Server, where Tableau is the ultimate server admin and you are at most a site admin within your sliver of the server, which would be the site delegated to your organization.

Regardless of whether it is Tableau Server, Tableau Online, or Tableau Cloud the REST API will be the same. What will change is which endpoints are supported, but the `tableau-api-lib` library can be used anywhere the REST API can be used.

Hope that helps!

**Comment by cmcau** [comment]
Sure, I know the difference between Server and Online/Cloud, but what are the settings to make it work?

At the moment I have this ...

`
# sample config
config = {
  'tableau_env': {
    'server': 'https://us-east-1.online.tableau.com',
    'api_version': '3.16',
    'personal_access_token_name': 'TOKEN NAME',
    'personal_access_token_secret': 'TOKEN CODE',
    'site_name': 'SITENAME',
    'site_url': 'https://us-east-1.online.tableau.com/#/site/SITENAME/workbooks'
  }
}


# configure connection and sign in
conn = TableauServerConnection(config, 'tableau_env')
conn.sign_in()
`

But it doesn't login and I've tried quite a few combinations of the site_url, using user/pass or PAT.

I got the code from https://towardsdatascience.com/query-tableau-workbook-permissions-for-all-groups-and-users-4ae4e4cc404  I don't have a Server to test it on, but I can't get it to work with Online.

**Comment by ascendmgt** [comment]
Sure, I know the difference between Server and Online/Cloud, but what are the settings to make it work?

At the moment I have this ...

```
# sample config
config = {
  'tableau_env': {
    'server': 'https://us-east-1.online.tableau.com',
    'api_version': '3.16',
    'personal_access_token_name': 'TOKEN NAME',
    'personal_access_token_secret': 'TOKEN CODE',
    'site_name': 'SITENAME',
    'site_url': 'https://us-east-1.online.tableau.com/#/site/SITENAME/workbooks'
  }
}


# configure connection and sign in
conn = TableauServerConnection(config, 'tableau_env')
conn.sign_in()
```

But it doesn't login and I've tried quite a few combinations of the site_url, using user/pass or PAT.

I got the code from https://towardsdatascience.com/query-tableau-workbook-permissions-for-all-groups-and-users-4ae4e4cc404  I don't have a Server to test it on, but I can't get it to work with Online.

**Comment by divinorum-webb** [comment]
@ascendmgt Ah, I see what you mean now.

One thing that jumps out is your `site_url` not being correct. This is supposed to be the site's name as it would appear in a URL. In many cases this is identical to the actual site name.

For example, consider my own Tableau Online config:
```
        'server': 'https://10ax.online.tableau.com/',
        'api_version': '3.16',
        "personal_access_token_name": <TOKEN_NAME>,
        "personal_access_token_secret": <TOKEN_SECRET>,
        'site_name': 'estamdevdev347987',
        'site_url': 'estamdevdev347987'
```

But now consider a site that has spaces between words, such as "My Site".
In this case the site name would be "My Site" but the site url (also known as content url) would be "My%20Site".

I have a tutorial explaining in more detail as well: https://medium.com/snake-charmer-python-and-analytics/tableau-server-on-tap-getting-started-89bc5f0095fa

Hope that helps! The rest of your config looks good.

**Comment by ascendmgt** [comment]
Ah, perfect, that works now :) 
Thanks for your help, this is a great resource :)

**Comment by Guipetris** [comment]
Great stuff! Had the same doubt and checked here before asking it! 👍

**Comment by Guipetris** [comment]
Hey - just followed the same thing as him but i'm getting this instead:

**Comment by divinorum-webb** [comment]
Hey Guilherme, the error you are getting is because querying sites is not
supported in Tableau Online. If it were, you would be able to see details
of all the other companies/individuals who have a site within Tableau
Online.

For Tableau Server, querying sites is useful because you can create
multiple sites for various purposes. However, with Tableau Online you are
given a single site on a massive Tableau Server that is managed by Tableau
itself. The highest permissions possible to you are that of 'Site
Administrator', so you can query your own site but you cannot make use of
the "Query Sites" endpoint.

If you are implementing code from a tutorial where sites are queried, you
would want to eliminate that portion of the logic when in the context of
Tableau Online (because you cannot query any sites that aren't your own).

Hope that helps!
