### ISSUE TITLE
ModuleNotFoundError: No module named 'tableau_api_lib'

### ISSUE THREAD

**Issue by satyamk28** [divinorum-webb/tableau-api-lib#94]
I have installed the library using command **pip install --upgrade tableau-api-lib**

It is also installed on my system

![image](https://user-images.githubusercontent.com/26164350/186675142-ccd3be2c-f263-4219-85d6-159645646fe9.png)

But when I am running in on Jupyter, I am getting error that 

![image](https://user-images.githubusercontent.com/26164350/186675357-054fa99d-46f3-4409-9f44-b7b0b1193ad0.png)

I have tried restarting the system and kernel.

**Comment by divinorum-webb** [comment]
This is most likely an issue with your environment. On a windows machine I've had issues with packages and Python environments before. Seeing `~/AppData/` in the file path makes me think there might be some of that weirdness at play for you.

I'd recommend creating a virtual environment and then activate that environment, install the package within that environment, and try again. If you're using PyCharm, the IDE can help you do this as well.

How to create a python virtual environment: https://docs.python.org/3/library/venv.html

**Comment by satyamk28** [comment]
Virtual environment worked like a charm. Thanks for the help.
