### ISSUE TITLE
Problems with get_views_dataframe API 3.16

### ISSUE THREAD

**Issue by mayaralp** [divinorum-webb/tableau-api-lib#96]
I'm using tableau_api_lib.utils.querying. get_views_dataframe function an error occurs

PaginationError: 
        The Tableau Server REST API method query_views_for_site did not return paginated results. 
        Please verify that your connection is logged in and has a valid auth token.
        If using personal access tokens, note that only one session can be active at a time using a single token.
        Also note that the extract_pages() method wrapping this call is intended for paginated results only.
        Not all Tableau Server REST API methods support pagination.

I checked access and it is working fine. I also can get results using other functions like get_workbooks_dataframe . And the issue occurs in only one site, the others are running fine.
Could you help e with this?

Thanks

**Comment by divinorum-webb** [comment]
Hi @mayaralp, I'm unable to reproduce the error. Can you confirm which version of `tableau-api-lib` you have?

If you run `pip list`, you'll see something like this: 
<img width="277" alt="image" src="https://user-images.githubusercontent.com/13069208/191077729-267c87b8-f73e-4e80-93d9-1e379f4e6ccb.png">

**Comment by mayaralp** [comment]
Hi @divinorum-webb thanks for the quick response. Follow as you need:
![image](https://user-images.githubusercontent.com/45518241/191083837-816566f2-be20-4118-acec-efe0ee185a6f.png)

**Comment by divinorum-webb** [comment]
Ok, that rules out having an issue related to an older version of the library.

What do you get back when hitting the `query_views_for_site` endpoint? You can access that from your connection -- something like `response = conn.query_views_for_site()`.

**Comment by mayaralp** [comment]
I can, I get a response 200.

**Comment by divinorum-webb** [comment]
What about the content within it? Is it empty or are you getting data for your views on the site?

**Comment by mayaralp** [comment]
I can get data in the content either.
![image](https://user-images.githubusercontent.com/45518241/191093319-8541861e-637b-4bf2-8574-d9d79c086929.png)

**Comment by divinorum-webb** [comment]
I'm not able to reproduce the error locally, however I did notice that you have nearly 12,000 views in your results and the pagination logic within the library defaults to 100 results per page. It's a long shot, but perhaps the high number of iterations required to retrieve your results is an issue. I pushed an update to the library increasing the default page size from 100 to 1,000. To test if this fixes the issue, you can run `pip install -U tableau-api-lib` and then run your code again.

If this doesn't resolve the issue then I'm out of ideas because I am unable to reproduce and troubleshoot the error on my end.

**Comment by mayaralp** [comment]
Is there a way for me to override the default page size? I have been able to reproduce this issue in postman with the REST api and it seems to be an issue with the paging and large page sizes. I am actually able to get successful responses with lower page sizes. We have opened a ticket with Tableau to investigate but a workaround would be for me to try this and set the page size myself.

**Comment by divinorum-webb** [comment]
Just added support for user-defined page size when querying views or users, looks like this:
`views_df = querying.get_views_dataframe(conn, page_size=1000)`.

Just run `pip install -U tableau-api-lib` to get the latest version of the lib.

**Comment by mayaralp** [comment]
Hi @divinorum-webb it worked passing page size as 1. Although it takes a long time to get all but it will work until I have an answer from Tableau.
Thanks for your support.
